site_name: Trading Wala Guru Course
site_url: https://Satyenderparihar.github.io/Trading-Wala-Guru/
repo_url: https://github.com/Satyenderparihar/Trading-Wala-Guru
repo_name: Satyenderparihar/Trading-Wala-Guru
docs_dir: Trading_Course

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: "https://www.instagram.com/satya_motivation?utm_source=qr&igsh=amxtc3FiNXhzcmVm"
      name: Instagram par follow karein
    - icon: fontawesome/brands/facebook
      link: "https://www.facebook.com/share/18DVYhUP53/"
      name: Facebook
    - icon: fontawesome/brands/whatsapp
      link: "https://wa.me/917976305274"
      name: Chat on WhatsApp
    - icon: fontawesome/brands/telegram
      link: https://t.me/Satyamotivation
      name: Telegram Community
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@SatyenderParihar
      name: YouTube par subscribe karein
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
  - with-pdf:
      cover: true
      cover_title: "Trading Wala Guru Course"
      toc_title: "Table of Contents"
      output_path: "pdfs/document.pdf"
      enabled_if_env: ENABLE_PDF_EXPORT
