//@version=6
indicator("Smoothed Gaussian Trend Filter [AlgoAlpha]", "AlgoAlpha - Smoothed Gaussian Trend", overlay = true)

// Gaussian Filter Settings
periodInput = input.int(15, title="Gaussian Length", group = "Gaussian Filter Settings")
polesInput = input.int(3, title="Poles", minval=1, maxval=4, group = "Gaussian Filter Settings")
linreglen = input.int(22, title="Smoothing Length", group = "Smoothing Settings")
linregoffset = input.int(7, title="Flatten Multiplier", group = "Smoothing Settings")

// Appearance
vol_int = input.bool(true, title="Volume Intensity", group = "Appearance")
green1 = input.color(#00ffbb, title="Bullish Color", group = "Appearance")
red1 = input.color(#ff1100, title="Bearish Color", group = "Appearance")

// Gaussian Math
calcGaussianAlpha(_length, _order) =>
    freq = (2.0 * math.pi) / _length
    factorB = (1.0 - math.cos(freq)) / (math.pow(1.414, (2.0 / _order)) - 1.0)
    alphaVal = -factorB + math.sqrt(factorB * factorB + 2.0 * factorB)
    alphaVal

gaussianSmooth(dataIn, filterLevel, alphaCoeff) =>
    var float runningFilterValue = 0.0
    oneMinusAlpha = 1.0 - alphaCoeff
    if filterLevel == 1
        runningFilterValue := alphaCoeff * dataIn + oneMinusAlpha * nz(runningFilterValue[1])
    else if filterLevel == 2
        runningFilterValue := (alphaCoeff * alphaCoeff) * dataIn + 2.0 * oneMinusAlpha * nz(runningFilterValue[1]) - (oneMinusAlpha * oneMinusAlpha) * nz(runningFilterValue[2])
    runningFilterValue

alphaValue = calcGaussianAlpha(periodInput, polesInput)
gmaOutput = gaussianSmooth(close, polesInput, alphaValue)
final = ta.linreg(gmaOutput, linreglen, linregoffset)

// Plots
trendColor = final > final[1] ? green1 : red1
plot(final, color=trendColor, linewidth=3, title="Gaussian Filter")

// Bar Coloring
barcolor(trendColor)
